# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: BUSL-1.1

# Add a Terraform label to changes under the related folders:
#
# Folder                      | Labels
# --------------------------- | ------------------------------------------------
# terraform                   | Terraform CE
# terraform-cdk               | None
# terraform-docs-agents       | Terraform agents
# terraform-docs-common       | HCP Terraform
# terraform-enterprise        | Terraform Enterprise
# terraform-migrate           | Terraform migrate
# terraform-plugin-framework  | TF Plugin Framework
# terraform-plugin-log        | None
# terraform-plugin-mux        | None
# terraform-plugin-sdk        | None
# terraform-plugin-testing    | None

Terraform CE:
- any:
  - changed-files:
    - any-glob-to-any-file: [
        'content/terraform/**'
      ]

Terraform agents:
- any:
  - changed-files:
    - any-glob-to-any-file: [
        'content/terraform-docs-agents/**'
      ]

HCP Terraform:
- any:
  - changed-files:
    - any-glob-to-any-file: [
        'content/terraform-docs-common/**'
      ]

Terraform Enterprise:
- any:
  - changed-files:
    - any-glob-to-any-file: [
        'content/terraform-enterprise/**'
      ]

Terraform migrate:
- any:
  - changed-files:
    - any-glob-to-any-file: [
        'content/terraform-migrate/**'
      ]

TF Plugin Framework:
- any:
  - changed-files:
    - any-glob-to-any-file: [
        'content/terraform-plugin-framework/**'
      ]


# Add 'Vault' label to changes under 'content/vault'
#
# Label           | Rule
# --------------- | ------------------------------------------------------------
# Vault           | Default; applies to all doc updates
# Vault IC update | Updates on "Important changes" related docs

Vault:
- any:
  - changed-files:
    - any-glob-to-any-file: [
        'content/vault/**'
      ]

Vault IC:
- any:
  - changed-files:
    - any-glob-to-any-file: [
        'content/vault/global/partials/important-changes/**',
        'content/vault/*/content/docs/updates/change-tracker.mdx',
        'content/vault/*/content/docs/updates/important-changes.mdx',
        'content/vault/*/content/docs/updates/lts-tracker.mdx'
      ]

# Add 'WAF' label to changes under 'content/well-architected-framework'
#
# Label           | Rule
# --------------- | ------------------------------------------------------------
# WAF             | Default; applies to all doc updates

WAF:
- any:
  - changed-files:
    - any-glob-to-any-file: [
        'content/well-architected-framework/**'
      ]

# Add 'Sentinel' label to changes under 'content/sentinel'
#
# Label           | Rule
# --------------- | ------------------------------------------------------------
# Sentinel        | Default; applies to all doc updates

Sentinel:
- any:
  - changed-files:
    - any-glob-to-any-file: [
        'content/sentinel/**'
      ]