name: Algolia Sync - Production

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'content/**/**/docs/**/*.mdx'

jobs:
  setup-and-update-algolia:
    name: Setup and Update Algolia
    runs-on: ubuntu-latest
    if: github.repository == 'hashicorp/web-unified-docs'
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          cache: 'npm'
          node-version-file: 'package.json'

      - run: npm ci
      - run: npm run prebuild -- --get-real-file-changed-metadata --build-algolia-index
      - run: npm run algolia
        env:
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY_PROD }}
          ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME_PROD}}
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
