name: Deploy UDR

on:
  push:
    branches:
      - 'main'

    paths:
      - 'content/**'
      - 'app/**'

  workflow_dispatch:

jobs:
  deploy-udr:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    if: github.repository == 'hashicorp/web-unified-docs'
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_TEAM_ID }} # The org id for HashiCorp in Vercel
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }} # The ID of the UDR Vercel project
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          cache: 'npm'
          node-version-file: 'package.json'

      - name: Cache Next.js build
        uses: actions/cache@a7833574556fa59680c1b7cb190c1735db73ebf0 # v5.0.0
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-build-${{ hashFiles('package-lock.json', 'next.config.js') }}

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} --logs --archive=tgz

      - name: Rebuild Dev Portal
        shell: bash
        run: |
          echo "Rebuilding all of dev-portal"
          curl -X POST ${{ secrets.DEV_PORTAL_DEPLOY_HOOK_PROD }}
