#
# This GitHub action runs basic linting checks for Packer.
#

name: "Go Validate"

on:
  push:
    branches:
      - 'main'
    paths:
      - 'content/packer/**'
  pull_request:
    paths:
      - 'content/packer/**'

permissions:
  contents: read

jobs:
  get-go-version:
    runs-on: ubuntu-latest
    outputs:
      go-version: ${{ steps.get-go-version.outputs.go-version }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: 'Determine Go version'
        id: get-go-version
        run: |
          echo "Found Go $(cat .go-version)"
          echo "go-version=$(cat .go-version)" >> $GITHUB_OUTPUT
  check-generate:
    needs:
      - get-go-version
    runs-on: ubuntu-latest
    name: Generate check
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: ${{ needs.get-go-version.outputs.go-version }}
      - run: make generate-check
